### ISSUE TITLE
We need a favicon

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/hoth.uclaacm.com#39]
Right now, we are still using Gatsby's default favicon. We should change it so that our own logo is used.

It's up to us which logo we should use: Hack's, or design a HOTH logo.

https://github.com/uclaacm/hoth.uclaacm.com/blob/cb22f273981aae54cbf495448619ab2ab3f0d501/gatsby-config.js#L27

**Comment by Timthetic** [comment]
Just for experimentation, I took screenshots with the hack logo and the logo from hoth7. I like the Hack logo a lot because it is simple, so it looks nice even though it is small. If we ask design to create one, it should be simple unlike the Hoth7 logo (which I'm sure was not designed with the intention of being used as a favicon). One idea is to have it be inspired off of the Hack logo, but look slightly different or more "intense".

<img width="1280" alt="Website-with-hack-logo" src="https://user-images.githubusercontent.com/33593205/85893476-cc1b8b00-b7a7-11ea-9716-1ce16a7c39fd.png">
<img width="1279" alt="Website-with-hoth-logo" src="https://user-images.githubusercontent.com/33593205/85893485-cf167b80-b7a7-11ea-8c39-90e02d0aeb8c.png">

**Comment by jamieliu386** [comment]
I think we should use the Hack logo for now because the current splashthat site uses it, and like you said, it's much cleaner than the hoth7 logo.

We can always design or get a new favicon in the future if we decide we want something different.

**Comment by TimothyGu** [comment]
Hack logo sounds good. We definitely should not use the HOTH logo, though I was hoping someone could come up with a simplified design for the HOTH logo.
