### ISSUE TITLE
Upcoming events on the homepage

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/hoth.uclaacm.com#42]
See [Figma](https://www.figma.com/file/sC4tsO37gn2qgn1ol1yfZq/HOTH-Website?node-id=0%3A1)

**Comment by Timthetic** [comment]
I thought this would be trivial, because I could just reuse the `TimeSlot` component. It seems that my assumption was incorrect. I'm unsure if I should try to adapt the `TimeSlot` component to work here or to create a new one.

<img width="954" alt="HoTH-dev-Upcoming" src="https://user-images.githubusercontent.com/33593205/85900226-4fdb7480-b7b4-11ea-9628-1f28c6813d75.png">

**Comment by TimothyGu** [comment]
Please submit a PR first so we can discuss!
