### ISSUE TITLE
Make the time slot heading sticky

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/hoth.uclaacm.com#59]

**Comment by milesswu** [comment]
In relation with pull request  #64, I'm unsure if the timeslots used on the HomePage's "Upcoming Workshops" section should have the same format/behavior as the SchedulePage. In other words, the question is whether the Upcoming Workshops section should also have sticky timeslot headers. If so, we can change the implementation in #64 so that both page's use the StickyTimeSlot component.

**Comment by TimothyGu** [comment]
I don't think the home page should have sticky headers. The home page will only have a few items at most

**Comment by milesswu** [comment]
Okay, in that case I think we can keep the changes as they are, unless someone knows a better way to do it.
